spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainings_test
    username: trainings_test
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true